package notifications.notification_model;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Represents a single in-app notification generated by the system.
 *
 * Notifications are produced by three sources:
 * - {@link Type#RECORDATORIO}      — A scheduled reminder has reached its trigger date.
 * - {@link Type#META_CUMPLIDA}     — A savings goal has reached its target amount.
 * - {@link Type#RECURRENTE_VENCIDO} — A recurring payment has been processed.
 *
 * Instances are managed by {@link NotificationManager}.
 */
public class AppNotification {

    /** Classification of the event that originated this notification. */
    public enum Tipo {
        RECORDATORIO,
        META_CUMPLIDA,
        RECURRENTE_VENCIDO
    }

    private static final DateTimeFormatter DISPLAY_FMT =
            DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

    private final Tipo tipo;
    private final String titulo;
    private final String cuerpo;
    private final LocalDateTime timestamp;
    private boolean leida;

    /**
     * Creates a new unread notification.
     *
     * @param tipo      source type of this notification
     * @param titulo    short title shown in the notification panel header
     * @param cuerpo    detailed description shown in the notification card body
     * @param timestamp moment when the event was detected
     */
    public AppNotification(Tipo tipo, String titulo, String cuerpo, LocalDateTime timestamp) {
        this.tipo = tipo;
        this.titulo = titulo;
        this.cuerpo = cuerpo;
        this.timestamp = timestamp;
        this.leida = false;
    }

    /** @return the classification of the originating event */
    public Tipo getTipo() { return tipo; }

    /** @return short notification title */
    public String getTitulo() { return titulo; }

    /** @return full notification body */
    public String getCuerpo() { return cuerpo; }

    /** @return moment the event was detected */
    public LocalDateTime getTimestamp() { return timestamp; }

    /** @return whether the user has already opened the notification panel since this arrived */
    public boolean isLeida() { return leida; }

    /** Marks this notification as read. */
    public void marcar() { this.leida = true; }

    /**
     * Returns a human-readable timestamp string formatted as {@code dd/MM/yyyy HH:mm}.
     *
     * @return formatted timestamp
     */
    public String getTimestampFormateado() {
        return timestamp.format(DISPLAY_FMT);
    }

    /**
     * Returns the Ikonli icon literal that corresponds to this notification type,
     * used by the notification panel cell factory.
     *
     * @return Ikonli icon literal string
     */
    public String getIconoLiteral() {
        return switch (tipo) {
            case RECORDATORIO       -> "mdi2b-bell-ring";
            case META_CUMPLIDA      -> "mdi2t-trophy";
            case RECURRENTE_VENCIDO -> "mdi2c-calendar-clock";
        };
    }

    @Override
    public String toString() {
        return String.format("[%s] %s — %s", tipo, titulo, getTimestampFormateado());
    }
}
