package accounts.account_view;

public class AccountEditView extends javax.swing.JFrame {

        /**
         * Creates new form ViewEditAccount
         */
        public AccountEditView() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel5 = new javax.swing.JPanel();
                lblTittle = new javax.swing.JLabel();
                jPanel4 = new javax.swing.JPanel();
                lblNewNameAccount = new javax.swing.JLabel();
                lblNewType = new javax.swing.JLabel();
                lblNewCurrency = new javax.swing.JLabel();
                txtNameAccount = new javax.swing.JTextField();
                jScrollPane1 = new javax.swing.JScrollPane();
                listAccountType = new javax.swing.JList<>();
                jScrollPane2 = new javax.swing.JScrollPane();
                listCurrency = new javax.swing.JList<>();
                btnConfirm = new javax.swing.JButton();
                btnCancel = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(245, 144, 68));

                jPanel5.setBackground(new java.awt.Color(246, 107, 14));

                lblTittle.setFont(new java.awt.Font("Inter", 1, 28)); // NOI18N
                lblTittle.setForeground(new java.awt.Color(255, 255, 255));
                lblTittle.setText("EDITAR CUENTA");

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addGap(140, 140, 140)
                                                                .addComponent(lblTittle)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel5Layout.setVerticalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(lblTittle,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                44,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(14, Short.MAX_VALUE)));

                jPanel4.setBackground(new java.awt.Color(239, 239, 239));

                lblNewNameAccount.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lblNewNameAccount.setForeground(new java.awt.Color(17, 43, 60));
                lblNewNameAccount.setText("Nuevo nombre:");

                lblNewType.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lblNewType.setForeground(new java.awt.Color(17, 43, 60));
                lblNewType.setText("Nuevo tipo:");

                lblNewCurrency.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lblNewCurrency.setForeground(new java.awt.Color(17, 43, 60));
                lblNewCurrency.setText("Nueva moneda:");

                txtNameAccount.setBackground(new java.awt.Color(210, 210, 210));
                txtNameAccount.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
                txtNameAccount.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtNameAccountActionPerformed(evt);
                        }
                });

                listAccountType.setBackground(new java.awt.Color(89, 137, 169));
                listAccountType.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
                listAccountType.setForeground(new java.awt.Color(255, 255, 255));
                listAccountType.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "Cash", "Digital" };

                        public int getSize() {
                                return strings.length;
                        }

                        public String getElementAt(int i) {
                                return strings[i];
                        }
                });
                listAccountType.setSelectionBackground(new java.awt.Color(210, 210, 210));
                listAccountType.setSelectionForeground(new java.awt.Color(89, 137, 169));
                jScrollPane1.setViewportView(listAccountType);

                listCurrency.setBackground(new java.awt.Color(89, 137, 169));
                listCurrency.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
                listCurrency.setForeground(new java.awt.Color(255, 255, 255));
                listCurrency.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "MXN", "USD" };

                        public int getSize() {
                                return strings.length;
                        }

                        public String getElementAt(int i) {
                                return strings[i];
                        }
                });
                listCurrency.setSelectionBackground(new java.awt.Color(210, 210, 210));
                listCurrency.setSelectionForeground(new java.awt.Color(89, 137, 169));
                jScrollPane2.setViewportView(listCurrency);

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel4Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(lblNewNameAccount,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                193,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(txtNameAccount))
                                                                                .addGroup(jPanel4Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel4Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(jPanel4Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(lblNewCurrency,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                193,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(jScrollPane2,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                66,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGroup(jPanel4Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(lblNewType,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                193,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(jScrollPane1,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                93,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                .addGap(0, 183, Short.MAX_VALUE)))
                                                                .addContainerGap()));
                jPanel4Layout.setVerticalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGap(33, 33, 33)
                                                                .addGroup(jPanel4Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(txtNameAccount)
                                                                                .addComponent(lblNewNameAccount,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                44,
                                                                                                Short.MAX_VALUE))
                                                                .addGap(31, 31, 31)
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(lblNewType,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                44,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jScrollPane1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                52,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                27,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(lblNewCurrency,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                44,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jScrollPane2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                50,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(19, 19, 19)));

                btnConfirm.setBackground(new java.awt.Color(32, 83, 117));
                btnConfirm.setFont(new java.awt.Font("Inter", 1, 28)); // NOI18N
                btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
                btnConfirm.setText("Confirmar");
                btnConfirm.setBorder(null);
                btnConfirm.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnConfirmActionPerformed(evt);
                        }
                });

                btnCancel.setBackground(new java.awt.Color(179, 65, 65));
                btnCancel.setFont(new java.awt.Font("Inter", 1, 28)); // NOI18N
                btnCancel.setForeground(new java.awt.Color(255, 255, 255));
                btnCancel.setText("Cancelar");
                btnCancel.setBorder(null);
                btnCancel.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCancelActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(17, 17, 17)
                                                                .addGroup(jPanel1Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(jPanel4,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(btnCancel,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                220,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(btnConfirm,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                220,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(15, Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jPanel5,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jPanel4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                38,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnConfirm,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                88,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(btnCancel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                88,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(24, 24, 24)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE));

                pack();
        }

        private void txtNameAccountActionPerformed(java.awt.event.ActionEvent evt) {

        }

        private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {

        }

        private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {

        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(AccountEditView.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(AccountEditView.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(AccountEditView.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(AccountEditView.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new AccountEditView().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify
        private javax.swing.JButton btnCancel;
        private javax.swing.JButton btnConfirm;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JLabel lblNewCurrency;
        private javax.swing.JLabel lblNewNameAccount;
        private javax.swing.JLabel lblNewType;
        private javax.swing.JLabel lblTittle;
        private javax.swing.JList<String> listAccountType;
        private javax.swing.JList<String> listCurrency;
        private javax.swing.JTextField txtNameAccount;
        // End of variables declaration

        public javax.swing.JTextField getTxtNameAccount() {
                return txtNameAccount;
        }

        public javax.swing.JList<String> getListAccountType() {
                return listAccountType;
        }

        public javax.swing.JList<String> getListCurrency() {
                return listCurrency;
        }

        public javax.swing.JButton getBtnConfirm() {
                return btnConfirm;
        }

        public javax.swing.JButton getBtnCancel() {
                return btnCancel;
        }
}
