package accounts.account_view;

import java.util.List;

import javax.swing.DefaultListModel;

import accounts.account_model.Account;

public class AccountView extends javax.swing.JFrame {

        public AccountView() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel3 = new javax.swing.JPanel();
                btnAddAccount = new javax.swing.JButton();
                jPanel4 = new javax.swing.JPanel();
                lblNameAccount = new javax.swing.JLabel();
                lblTypeAccount = new javax.swing.JLabel();
                lblCoinAccount = new javax.swing.JLabel();
                lblCurencyAccount = new javax.swing.JLabel();
                txtInitialBalance = new javax.swing.JTextField();
                txtNameAccount = new javax.swing.JTextField();
                jScrollPane1 = new javax.swing.JScrollPane();
                listAccountType = new javax.swing.JList<>();
                jScrollPane2 = new javax.swing.JScrollPane();
                listCurrency = new javax.swing.JList<>();
                jPanel2 = new javax.swing.JPanel();
                jScrollPane3 = new javax.swing.JScrollPane();
                listAccounts = new javax.swing.JList<>();
                btnEditAccount = new javax.swing.JButton();
                btnDeleteAccount = new javax.swing.JButton();
                btnAccessAccount = new javax.swing.JButton();
                jPanel5 = new javax.swing.JPanel();
                lblTittle = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setBackground(new java.awt.Color(89, 137, 169));

                jPanel1.setBackground(new java.awt.Color(32, 83, 117));

                jPanel3.setBackground(new java.awt.Color(89, 137, 169));

                btnAddAccount.setBackground(new java.awt.Color(246, 107, 14));
                btnAddAccount.setFont(new java.awt.Font("Inter", 1, 28)); // NOI18N
                btnAddAccount.setForeground(new java.awt.Color(255, 255, 255));
                btnAddAccount.setText("Agregar Nueva Cuenta");
                btnAddAccount.setBorder(null);
                btnAddAccount.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAddAccountActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGap(52, 52, 52)
                                                                .addComponent(btnAddAccount,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                394,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGap(27, 27, 27)
                                                                .addComponent(btnAddAccount,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                88,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(27, Short.MAX_VALUE)));

                jPanel4.setBackground(new java.awt.Color(239, 239, 239));

                lblNameAccount.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lblNameAccount.setForeground(new java.awt.Color(17, 43, 60));
                lblNameAccount.setText("Nombre:");

                lblTypeAccount.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lblTypeAccount.setForeground(new java.awt.Color(17, 43, 60));
                lblTypeAccount.setText("Tipo:");

                lblCoinAccount.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lblCoinAccount.setForeground(new java.awt.Color(17, 43, 60));
                lblCoinAccount.setText("Moneda:");

                lblCurencyAccount.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                lblCurencyAccount.setForeground(new java.awt.Color(17, 43, 60));
                lblCurencyAccount.setText("Saldo inicial: $");

                txtInitialBalance.setBackground(new java.awt.Color(210, 210, 210));

                txtNameAccount.setBackground(new java.awt.Color(210, 210, 210));
                txtNameAccount.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N

                listAccountType.setBackground(new java.awt.Color(89, 137, 169));
                listAccountType.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
                listAccountType.setForeground(new java.awt.Color(255, 255, 255));
                listAccountType.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "Cash", "Digital" };

                        public int getSize() {
                                return strings.length;
                        }

                        public String getElementAt(int i) {
                                return strings[i];
                        }
                });
                listAccountType.setSelectionBackground(new java.awt.Color(210, 210, 210));
                listAccountType.setSelectionForeground(new java.awt.Color(89, 137, 169));
                jScrollPane1.setViewportView(listAccountType);

                listCurrency.setBackground(new java.awt.Color(89, 137, 169));
                listCurrency.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
                listCurrency.setForeground(new java.awt.Color(255, 255, 255));
                listCurrency.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "MXN", "USD" };

                        public int getSize() {
                                return strings.length;
                        }

                        public String getElementAt(int i) {
                                return strings[i];
                        }
                });
                listCurrency.setSelectionBackground(new java.awt.Color(210, 210, 210));
                listCurrency.setSelectionForeground(new java.awt.Color(89, 137, 169));
                jScrollPane2.setViewportView(listCurrency);

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGap(23, 23, 23)
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel4Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel4Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(lblCurencyAccount)
                                                                                                                .addComponent(lblNameAccount,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                109,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGroup(jPanel4Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(lblTypeAccount)
                                                                                                                                .addGap(26, 26, 26)
                                                                                                                                .addComponent(jScrollPane1,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                69,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(txtInitialBalance,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                209,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addGap(21, 21, 21))
                                                                                .addGroup(jPanel4Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(lblCoinAccount,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                109,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jScrollPane2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                66,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addContainerGap(
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE))))
                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                jPanel4Layout.createSequentialGroup()
                                                                                                .addContainerGap(154,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(txtNameAccount,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                263,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(21, 21, 21))));
                jPanel4Layout.setVerticalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGap(43, 43, 43)
                                                                .addComponent(lblNameAccount,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                44,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(62, 62, 62)
                                                                .addGroup(jPanel4Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(lblTypeAccount,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                44,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jScrollPane1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                0,
                                                                                                Short.MAX_VALUE))
                                                                .addGap(75, 75, 75)
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel4Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(lblCoinAccount,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                44,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                74,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addGroup(jPanel4Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(lblCurencyAccount,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                44,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(txtInitialBalance,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                44,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(46, 46, 46))
                                                                                .addGroup(jPanel4Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jScrollPane2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                50,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addContainerGap(
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE))))
                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                                .addGap(46, 46, 46)
                                                                                .addComponent(txtNameAccount)
                                                                                .addGap(386, 386, 386))));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(37, Short.MAX_VALUE)
                                                                .addComponent(jPanel4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(25, 25, 25)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(14, Short.MAX_VALUE)
                                                                .addComponent(jPanel4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jPanel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

                jPanel2.setBackground(new java.awt.Color(246, 107, 14));
                jPanel2.setForeground(new java.awt.Color(246, 107, 14));

                listAccounts.setBackground(new java.awt.Color(239, 239, 239));
                listAccounts.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
                listAccounts.setForeground(new java.awt.Color(32, 83, 117));
                listAccounts.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "Cuenta de Ahorros", "Bbva", "Mau's Account" };

                        public int getSize() {
                                return strings.length;
                        }

                        public String getElementAt(int i) {
                                return strings[i];
                        }
                });
                listAccounts.setSelectionBackground(new java.awt.Color(246, 107, 14));
                listAccounts.setSelectionForeground(new java.awt.Color(255, 255, 255));
                jScrollPane3.setViewportView(listAccounts);

                btnEditAccount.setBackground(new java.awt.Color(210, 210, 210));
                btnEditAccount.setFont(new java.awt.Font("Inter", 1, 28)); // NOI18N
                btnEditAccount.setForeground(new java.awt.Color(255, 255, 255));
                btnEditAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("../../images/image 30.png"))); // NOI18N
                btnEditAccount.setBorder(null);

                btnDeleteAccount.setBackground(new java.awt.Color(210, 210, 210));
                btnDeleteAccount.setFont(new java.awt.Font("Inter", 1, 28)); // NOI18N
                btnDeleteAccount.setForeground(new java.awt.Color(255, 255, 255));
                btnDeleteAccount.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("../../images/image 25.png"))); // NOI18N
                btnDeleteAccount.setBorder(null);

                btnAccessAccount.setBackground(new java.awt.Color(32, 83, 117));
                btnAccessAccount.setFont(new java.awt.Font("Inter", 1, 28)); // NOI18N
                btnAccessAccount.setForeground(new java.awt.Color(239, 239, 239));
                btnAccessAccount.setText("Entrar");
                btnAccessAccount.setBorder(null);

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(24, 24, 24)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(btnEditAccount,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                71,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(btnDeleteAccount,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                71,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(btnAccessAccount,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                277,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(jScrollPane3,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                449,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(27, Short.MAX_VALUE)));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(16, 16, 16)
                                                                .addComponent(jScrollPane3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                477,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(btnEditAccount,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                70,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(btnDeleteAccount,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                70,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(btnAccessAccount,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                70,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(41, 41, 41)));

                jPanel5.setBackground(new java.awt.Color(89, 137, 169));

                lblTittle.setFont(new java.awt.Font("Inter", 1, 28)); // NOI18N
                lblTittle.setForeground(new java.awt.Color(255, 255, 255));
                lblTittle.setText("GESTIÓN DE CUENTAS");

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(lblTittle)
                                                                .addGap(339, 339, 339)));
                jPanel5Layout.setVerticalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(lblTittle,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                44,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(14, Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jPanel1,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jPanel2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(jPanel5,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap()));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addComponent(jPanel5,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(jPanel2,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jPanel1,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))));

                pack();
        }// </editor-fold>

        public void updateAccountList(List<Account> accounts) {
                DefaultListModel<String> listModel = new DefaultListModel<>();

                for (Account account : accounts) {
                        String display = String.format("%s (%.2f %s)",
                                        account.getName(),
                                        account.getCurrentBalance(),
                                        account.getCoin());

                        listModel.addElement(display);
                }

                listAccounts.setModel(listModel);
        }

        private void btnAddAccountActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
        }

        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(AccountView.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(AccountView.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(AccountView.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(AccountView.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new AccountView().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify
        public javax.swing.JButton btnAddAccount;
        private javax.swing.JButton btnDeleteAccount;
        private javax.swing.JButton btnAccessAccount;
        private javax.swing.JButton btnEditAccount;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JLabel lblCoinAccount;
        private javax.swing.JLabel lblCurencyAccount;
        private javax.swing.JLabel lblNameAccount;
        private javax.swing.JLabel lblTittle;
        private javax.swing.JLabel lblTypeAccount;
        public javax.swing.JList<String> listAccountType;
        private javax.swing.JList<String> listAccounts;
        public javax.swing.JList<String> listCurrency;
        public javax.swing.JTextField txtInitialBalance;
        public javax.swing.JTextField txtNameAccount;
        // End of variables declaration

        public javax.swing.JButton getBtnAccessAccount() {
                return btnAccessAccount;
        }

        public javax.swing.JButton getBtnAddAccount() {
                return btnAddAccount;
        }

        public String getAccountName() {
                return txtNameAccount.getText();
        }

        public String getInitialBalanceText() {
                return txtInitialBalance.getText();
        }

        public String getSelectedAccountType() {
                return listAccountType.getSelectedValue();
        }

        public String getSelectedCurrency() {
                return listCurrency.getSelectedValue();
        }

        public javax.swing.JButton getBtnDeleteAccount() {
                return btnDeleteAccount;
        }

        public javax.swing.JList<String> getListAccounts() {
                return listAccounts;
        }

        public javax.swing.JButton getBtnEditAccount() {
                return btnEditAccount;
        }
}